### ISSUE TITLE
Data Visualization using Tableau

### ISSUE THREAD

**Issue by tanveesrivastava** [iamsivab/ama#1]
I am trying to learn Tableau. Yesterday I tried installing it but it is not for 32 bit operating system. How can I learn Tableau practically then because my system is 32 bit. Because all the online courses recommend using Tableau Desktop.

**Comment by storieswithsiva** [comment]
Hey Hi,

I hope you can use Flourish which is an Online Visualisation Tool. I hope I have answered your Query!
